<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE menu [
        <!ELEMENT menu (piatti+,menudelgiorno)>
        <!ELEMENT piatti (primo|secondo)*>
        <!ELEMENT primo (nome,prezzo,descrizione)>
        <!ELEMENT secondo (nome,prezzo,descrizione)>
        <!ELEMENT nome (#PCDATA)>
        <!ELEMENT prezzo (#PCDATA)>
        <!ELEMENT descrizione (#PCDATA)>
        <!ATTLIST primo id ID #REQUIRED>
        <!ATTLIST secondo id ID #REQUIRED>
        <!ELEMENT menudelgiorno (piatto*)>
        <!ATTLIST menudelgiorno giorno CDATA #REQUIRED>
        <!ELEMENT piatto EMPTY>
        <!ATTLIST piatto idRef IDREF #REQUIRED>
        ]>
<menu>
    <piatti>
        <primo id="a00001">
            <nome>Pasta al Pomodoro</nome>
            <prezzo>5</prezzo>
            <descrizione>Spaghettoni De Cecco con salsa di pomodoro.</descrizione>
        </primo>
        <primo id="a00002">
            <nome>Pasta al Pesto</nome>
            <prezzo>5</prezzo>
            <descrizione>Trofie acqua e farinoa con pesto D.O.P.</descrizione>
        </primo>
        <primo id="a00003">
            <nome>Tortellini alla Norcina</nome>
            <prezzo>7</prezzo>
            <descrizione>Tortellini di carne con panna funghi e salsiccia.</descrizione>
        </primo>
        <secondo id="a00010">
            <nome>Bistecca ai Ferri</nome>
            <prezzo>9</prezzo>
            <descrizione>Controfiletto di Manzo cotto alla griglia.</descrizione>
        </secondo>
        <secondo id="a00011">
            <nome>Pollo al Forno</nome>
            <prezzo>8</prezzo>
            <descrizione>Pollo cotto al forno con patate arrosto.</descrizione>
        </secondo>
    </piatti>
    <menudelgiorno giorno="12/03/2023">
        <piatto idRef="a00001"/>
        <piatto idRef="a00003"/>
        <piatto idRef="a00010"/>
    </menudelgiorno>
</menu>